name: flutter_sqlite_database
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #Drift (SQLite Database)
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.42

  #Path 
  path: ^1.9.1
  path_provider: ^2.1.5

  # Riverpod(state management)
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  #code generation 
  json_annotation: ^4.11.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  #Drift
  drift_dev: ^2.20.0

  #Runner 
  build_runner: ^2.13.1

  #Riverpod
  riverpod_generator: ^4.0.3

  # code generation
  freezed: ^3.2.5
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
